name: Build Installer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      - name: Prepare build
        run: |
          # Создаем папку Output
          if (!(Test-Path Output)) { New-Item -ItemType Directory -Path Output }
          # Проверяем наличие exe-файла
          if (!(Test-Path "lab5.exe")) {
              Write-Error "lab5.exe not found!"
              Get-ChildItem -Recurse | Format-Table Name
              exit 1
          }

      - name: Build installer
        run: |
          ISCC.exe setup.iss
          if ($LASTEXITCODE -ne 0) {
              # Выводим подробный лог ошибок
              Get-Content "setup.ilg" | ForEach-Object { Write-Output $_ }
              exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Output\Setup.exe
