name: Build Installer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история для тегов

      # Шаг 1: Определяем версию
      - name: Set version
        id: set-version
        run: |
          # Если version.txt существует - берем оттуда, иначе используем git describe
          if (Test-Path version.txt) {
              $version = Get-Content version.txt -Raw
          } else {
              $version = git describe --tags --abbrev=0
              if (-not $version) { $version = "1.0.0" }
          }
          $version = $version.Trim()
          echo "Using version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT
          # Обновляем version.txt
          echo $version > version.txt

      # Шаг 2: Установка Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      # Шаг 3: Проверка файлов
      - name: Verify files
        run: |
          $exePath = "lab5/bin/Debug/lab5.exe"
          if (!(Test-Path $exePath)) {
              Write-Error "Файл $exePath не найден!"
              Get-ChildItem -Recurse | Format-Table FullName
              exit 1
          }

      # Шаг 4: Сборка
      - name: Build installer
        run: |
          ISCC.exe /O"." /F"Installer_${{ steps.set-version.outputs.version }}" /DMyAppVersion="${{ steps.set-version.outputs.version }}" setup.iss
          if ($LASTEXITCODE -ne 0) {
              Get-Content "setup.ilg" | ForEach-Object { Write-Output $_ }
              exit 1
          }

      # Шаг 5: Публикация артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Installer_${{ steps.set-version.outputs.version }}.exe
          retention-days: 7
