name: Build and Release Installer

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 1: Определение версии
      - name: Set version
        id: set-version
        run: |
          $commitMsg = git log -1 --pretty=%B
          if ($commitMsg -match '(\d+\.\d+\.\d+)') {
              $version = $matches[0]
          } else {
              $version = Get-Date -Format "yyyy.MM.dd"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          Set-Content -Path version.txt -Value $version

      # Шаг 2: Установка Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      # Шаг 3: Подготовка папок
      - name: Prepare directories
        run: |
          Remove-Item -Path "dist" -Recurse -ErrorAction Ignore
          New-Item -ItemType Directory -Path "dist" -Force

      # Шаг 4: Сборка установщика
      - name: Build installer
        run: |
          $version = "${{ steps.set-version.outputs.version }}"
          $outputName = "MyApp_$version"  # Без .exe в конце!
          
          Write-Output "Building version: $version"
          ISCC.exe /O"dist" /F"$outputName" /DMyAppVersion="$version" setup.iss
          
          # Проверяем результат
          if (-not (Test-Path "dist\$outputName.exe")) {
              Write-Output "##[error] Installer not found!"
              Get-ChildItem -Recurse
              exit 1
          }

      # Шаг 5: Создание релиза
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
          tag_name: v${{ steps.set-version.outputs.version }}
          name: Version ${{ steps.set-version.outputs.version }}
          body: |
            Автоматически собранный установщик
            Версия: ${{ steps.set-version.outputs.version }}
            Дата сборки: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
