name: Build and Deploy Installer

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Даем права на запись

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 1: Определение версии
      - name: Set version
        id: set-version
        run: |
          $commitMsg = git log -1 --pretty=%B
          if ($commitMsg -match '\d+\.\d+\.\d+') {
              $version = $matches[0]
          } else {
              $version = Get-Date -Format "yyyy.MM.dd"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          Set-Content -Path version.txt -Value $version

      # Шаг 2: Установка Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      # Шаг 3: Сборка
      - name: Build installer
        run: |
          $installer = "MyApp_${{ steps.set-version.outputs.version }}.exe"
          ISCC.exe /O"." /F"$installer" /DMyAppVersion="${{ steps.set-version.outputs.version }}" setup.iss

      # Шаг 4: Публикация релиза
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            MyApp_${{ steps.set-version.outputs.version }}.exe
          tag_name: v${{ steps.set-version.outputs.version }}
          name: Version ${{ steps.set-version.outputs.version }}
          body: |
            Automatic release for version ${{ steps.set-version.outputs.version }}
            - Built on: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
