name: Build Installer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      - name: Set version
        id: set-version
        run: |
          # Проверяем version.txt или используем git tag
          if (Test-Path version.txt) {
              $version = Get-Content version.txt -Raw
          } else {
              $version = git describe --tags --abbrev=0
              if (-not $version) { $version = "1.0.0" }
          }
          $version = $version.Trim()
          echo "Using version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Verify ISS file
        run: |
          # Проверяем существование файла
          if (!(Test-Path setup.iss)) {
              Write-Error "setup.iss not found!"
              exit 1
          }
          # Проверяем синтаксис
          ISCC.exe /Q /DMyAppVersion="1.0.0" setup.iss /compileonly

      - name: Build installer
        run: |
          ISCC.exe /Qp /DMyAppVersion="${{ steps.set-version.outputs.version }}" setup.iss
          if ($LASTEXITCODE -ne 0) {
              # Детальный лог ошибки
              Get-Content "setup.ilg" | ForEach-Object { Write-Output $_ }
              exit $LASTEXITCODE
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Output\*.exe
          retention-days: 3
