name: Update and Build

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-and-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 1: Обновление version.txt
      - name: Update version file
        id: update-version
        run: |
          $message = git log -1 --pretty=%B $env:GITHUB_SHA
          $cleanMessage = $message.Trim() -replace "`n|`r", ""
          Set-Content -Path version.txt -Value $cleanMessage
          echo "message=$cleanMessage" >> $env:GITHUB_OUTPUT
          echo "Updated version.txt with: $cleanMessage"

      # Шаг 2: Установка Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      # Шаг 3: Сборка установщика
      - name: Build installer
        run: |
          $version = Get-Content version.txt -Raw
          ISCC.exe /DMyAppVersion="$version" setup.iss
          echo "Built installer with version: $version"

      # Шаг 4: Фиксация изменений
      - name: Commit version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Auto-update version to $(Get-Content version.txt)" || exit 0
          git push || exit 0

      # Шаг 5: Публикация артефакта (исправленная версия)
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Output/*.exe
          retention-days: 5
