name: Update Version File

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем полную историю коммитов
      
      - name: Write commit hash to file
        run: echo "${{ github.sha }}" > version.txt
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Update version to commit ${{ github.sha }}"
          git push
