name: Update Version File

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем полную историю коммитов
      
      - name: Get commit message
        id: get-commit
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "message=${MESSAGE}" >> $GITHUB_OUTPUT
      
      - name: Write commit message to file
        run: echo "${{ steps.get-commit.outputs.message }}" > version.txt
