name: Update and Build

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-and-build:
    runs-on: windows-latest  # Изменили на windows для ISCC
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 1: Обновление version.txt
      - name: Update version file
        id: update-version
        run: |
          # Получаем чистое сообщение коммита
          COMMIT_MESSAGE=$(git log -1 --pretty=%B ${{ github.sha }} | tr -d '\n' | xargs)
          echo "$COMMIT_MESSAGE" > version.txt
          echo "Updated version.txt with: $COMMIT_MESSAGE"

      # Шаг 2: Установка Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      # Шаг 3: Сборка установщика
      - name: Build installer
        run: |
          # Читаем версию из файла
          $version = Get-Content version.txt -Raw
          # Компилируем с передачей версии
          ISCC.exe /DMyAppVersion="$version" setup.iss

      # Шаг 4: Фиксация изменений version.txt
      - name: Commit version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Auto-update version to ${{ steps.update-version.outputs.message }}" || echo "No changes to commit"
          git push || echo "Nothing to push"

      # Шаг 5: Публикация артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: Output/*.exe  # Путь где ISCC создаёт установщик
