name: Update Version File

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

      - name: Get clean commit message
        id: commit-info
        run: |
          # Получаем только сообщение коммита (без хэша, автора и даты)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B ${{ github.sha }})
          # Удаляем все переносы строк и лишние пробелы
          CLEAN_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '\n' | xargs)
          echo "message=$CLEAN_MESSAGE" >> $GITHUB_OUTPUT

      - name: Update version file
        run: |
          # Полностью очищаем файл
          : > version.txt
          # Записываем только сообщение коммита
          echo "${{ steps.commit-info.outputs.message }}" > version.txt
          
      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build
        run: |
          # Читаем версию
          $version = Get-Content "version.txt" -Raw
          # Генерируем установщик
          ISCC.exe /DMyAppVersion=$version setup.iss
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: Output/*.exe

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Automatic version file update"
          git push
