name: Update Version File

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем полную историю коммитов
      
      - name: Get commit message
        id: get-commit
        run: |
          # Получаем сообщение именно этого коммита (не последнего в истории)
          MESSAGE="${{ github.event.head_commit.message }}"
          echo "message=${MESSAGE}" >> $GITHUB_OUTPUT
      
      - name: Write commit message to file
        run: |
          echo "${{ steps.get-commit.outputs.message }}" > version.txt
          cat version.txt  # Для отладки (можно удалить)
