name: Update Version File

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов для точного определения

      - name: Get current commit message
        id: commit-info
        run: |
          # Получаем точное сообщение текущего коммита
          COMMIT_MESSAGE=$(git log -1 --pretty=%B ${{ github.sha }})
          # Удаляем переносы строк для чистого вывода
          CLEAN_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '\n')
          echo "message=${CLEAN_MESSAGE}" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Write to version file
        run: |
          echo "Commit: ${{ steps.commit-info.outputs.sha }}" > version.txt
          echo "Message: ${{ steps.commit-info.outputs.message }}" >> version.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Update version info for ${{ steps.commit-info.outputs.sha }}"
          git push
